;; -*- Mode: Lisp; -*-

;; Rebind prefix Ctrl-X to Ctrl-U for convinience in Dvorak
;; Based on /Applications/LispWorks\ Personal\ 6.1/Library/lib/6-1-0-0/config/mac-key-binds.lisp

(in-package "CL-USER")

(flet ((dvorak-bind-key (command key &rest specific)
         (if specific
             (apply 'editor:bind-key command key specific)
           (editor:bind-key command key :global))))

(dvorak-bind-key "Set Prefix Argument" "Control-x")

;; Emacs Control-x bindings
(dvorak-bind-key "What Cursor Position" #("Control-u" "=")) ;MJS 10Jul93: added emacs-like binding
(dvorak-bind-key "Previous Page" #("Control-u" "["))
(dvorak-bind-key "Next Page" #("Control-u" "]"))
(dvorak-bind-key "Mark Page" #("Control-u" "Control-p"))
(dvorak-bind-key "Count Lines Page" #("Control-u" "l"))
(dvorak-bind-key "Mark Whole Buffer" #("Control-u" "h"))
(dvorak-bind-key "Exchange Point and Mark" #("Control-u" "Control-u"))
;; ignore register commands
;;(dvorak-bind-key "Point to Register" #("Control-u" "/"))
;;(dvorak-bind-key "Jump to Register" #("Control-u" "j"))
;;(dvorak-bind-key "Copy to Register" #("Control-u" "x"))
;;(dvorak-bind-key "Insert Register" #("Control-u" "g"))
(dvorak-bind-key "Uppercase Region" #("Control-u" "Control-u"))
(dvorak-bind-key "Lowercase Region" #("Control-u" "Control-l"))
(dvorak-bind-key "Delete Blank Lines" #("Control-u" "Control-o") :global)
(dvorak-bind-key "Forward Kill Sentence" #("Control-u" "Delete"))
(dvorak-bind-key "Backward Kill Sentence" #("Control-u" "Backspace"))
(dvorak-bind-key "Undo" "Control-z")
(dvorak-bind-key "Transpose Lines" #("Control-u" "Control-t"))
(dvorak-bind-key "Indent Rigidly" #("Control-u" "Tab"))
(dvorak-bind-key "Indent Rigidly" #("Control-u" "Control-i"))
(dvorak-bind-key "Set Fill Prefix" #("Control-u" "."))
(dvorak-bind-key "Set Fill Column" #("Control-u" "f"))
(dvorak-bind-key "Next Search Match" #("Control-u" "`"))
(dvorak-bind-key "Wfind File" #("Control-u" "Control-f"))
(dvorak-bind-key "Find Alternate File" #("Control-u" "Control-v"))
(dvorak-bind-key "Write File" #("Control-u" "Control-w"))
(dvorak-bind-key "Save File" #("Control-u" "Control-s"))
(dvorak-bind-key "Save All Files" #("Control-u" "s"))
(dvorak-bind-key "Save All Files and Exit" #("Control-u" "Control-c"))
(dvorak-bind-key "Insert File" #("Control-u" "i"))
(dvorak-bind-key "List Directory" #("Control-u" "d"))
(dvorak-bind-key "Select Buffer" #("Control-u" "b"))
(dvorak-bind-key "List Buffers" #("Control-u" "Control-b"))
(dvorak-bind-key "Kill Buffer" #("Control-u" "k"))
(dvorak-bind-key "Check Buffer Modified" #("Control-u" "~"))
(dvorak-bind-key "Toggle Buffer Read-Only" #("Control-u" "Control-q"))
(dvorak-bind-key "New Window" #("Control-u" "2")) 
(dvorak-bind-key "Next Ordinary Window" #("Control-u" "o"))
(dvorak-bind-key "Delete Window" #("Control-u" "0")) ; added 13/2/89 (MSM)
(dvorak-bind-key "Delete Other Windows" #("Control-u" "1"))
(dvorak-bind-key "Add Mode Word Abbrev" #("Control-u" "Control-a"))
(dvorak-bind-key "Add Global Word Abbrev" #("Control-u" "+"))
(dvorak-bind-key "Inverse Add Mode Word Abbrev" #("Control-u" "Control-h"))
(dvorak-bind-key "Inverse Add Global Word Abbrev" #("Control-u" "-"))
(dvorak-bind-key "Set Comment Column" #("Control-u" ";"))
;;(dvorak-bind-key "Evaluate Last Form" #("Control-u" "Control-e"))
(dvorak-bind-key "Evaluate Last Form In Listener" #("Control-u" "Control-e"))
(dvorak-bind-key "Define Keyboard Macro" #("Control-u" "("))
(dvorak-bind-key "End Keyboard Macro" #("Control-u" ")"))
(dvorak-bind-key "Last Keyboard Macro" #("Control-u" "e"))
(dvorak-bind-key "Keyboard Macro Query" #("Control-u" "q"))
;;(dvorak-bind-key "Illegal" #("Control-u" "b") :mode "Pc Echo")
;;(dvorak-bind-key "Illegal" #("Control-u" "Control-w") :mode "Pc Echo")
;;(dvorak-bind-key "Illegal" #("Control-u" "i") :mode "Pc Echo")
;;(dvorak-bind-key "Illegal" #("Control-u" "Control-s") :mode "Pc Echo")
;;(dvorak-bind-key "Illegal" #("Control-u" "Control-v") :mode "Pc Echo")
;;(dvorak-bind-key "Illegal" #("Control-u" "k") :mode "Pc Echo")
(dvorak-bind-key "Select Buffer Other Window" #("Control-u" "4" "b"))
); flet
